<a href="https://colab.research.google.com/github/afdmoraes/IA-RedesNeurais/blob/main/2_Rede_Neural_Feed_Forward.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Problema

Vamos treinar a rede neural de forma que ela possa prever o valor de saída correto quando fornecida com um novo conjunto de dados.

In [ ]:
import numpy as np

In [ ]:
#Matrix (4x3)
treinamento_entrada = np.array([[0, 0, 1],
                                [1, 1, 1],
                                [1, 0, 1],
                                [0, 1, 1]])

In [ ]:
type(treinamento_entrada)

numpy.ndarray

In [ ]:
treinamento_entrada

array([[0, 0, 1],
       [1, 1, 1],
       [1, 0, 1],
       [0, 1, 1]])

In [ ]:
treinamento_resultado = np.array([[0, 1, 1, 0]]).T

In [ ]:
treinamento_resultado

array([[0],
       [1],
       [1],
       [0]])

In [ ]:
np.random.seed(1)

In [ ]:
pesos_sinapticos = 2 * np.random.random((3,1)) - 1

In [ ]:
pesos_sinapticos

array([[-0.16595599],
       [ 0.44064899],
       [-0.99977125]])

In [ ]:
def sigmoid(x):
  return 1/(1 + np.exp(-x))

In [ ]:
def sigmoid_derivate(x):
  return x * (1-x)

In [ ]:
for i in range(10000):
  input_layer = treinamento_entrada
  output = sigmoid(np.dot(input_layer, pesos_sinapticos))

  erro = treinamento_resultado - output
  ajuste = erro * sigmoid_derivate(output)

  pesos_sinapticos += np.dot(input_layer.T, ajuste)

In [ ]:
pesos_sinapticos

array([[ 9.67401695],
       [-0.20784111],
       [-4.63015063]])

In [ ]:
print(output)

[[0.00553519]
 [0.9954841 ]
 [0.99632083]
 [0.00451045]]


In [ ]:
0, 1, 1, 0